[package]
name = "cargo"
version = "0.1.0"
authors = ["ts25504 <ts25504@gmail.com>"]
edition = "2018"

[lib]
name = "greetings"
crate-type = ["dylib"]

[target.'cfg(target_os="android")'.dependencies]
jni = {version = "0.10", default-features = false}

[dependencies]
